services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-generator-api
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - DEBUG=true
      - SERVER_PORT=8080
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - AI_ENABLE_CACHE=true
      - AI_MAX_CONCURRENT_REQUESTS=5
      - AI_REQUEST_TIMEOUT=30
      - AI_RETRY_COUNT=3
      - AI_RETRY_DELAY=1
      - IMAGE_MAX_SIZE=5242880
      - IMAGE_ALLOWED_TYPES=image/jpeg,image/png
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 